/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
}

fun deleteFileDir(f: File) {
    if (f.isDirectory) {
        f.listFiles().forEach { file ->
            deleteFileDir(file)
        }
    }
    f.delete()
}

tasks.getByName("clean").doFirst {
    // 清除maven的生成目录
    var file = File(projectDir.absolutePath + "/target")
    if (file.exists()) {
        deleteFileDir(file)
    }
    // 清除日志的目录
    file = File(projectDir.absolutePath + "/logs")
    if (file.exists()) {
        deleteFileDir(file)
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
    options.compilerArgs.add("-Xlint:none")
}